version: "3.8"

services: 
    aplicacion:
        build:
            context: .
            dockerfile: Dockerfile
        image: valorpass
        command: npm start
        ports:
            - 4000:4000

